language: node_js
node_js:
  - "10"
before_script:
  - npm install
  - git config user.name "zzz1220"
  - git config user.email "18352539920@163.com"
  - sed -i'' "s~https://github.com/zzz1220/blog.git~https://${gh_token}@github.com/zzz1220/blog.git~" _config.yml
script:
  - hexo generate
  - gulp
  - hexo deploy
