name: deploy_my_blog
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - name: Prepare ssh env
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts          
        env:
          SSH_DEPLOY_KEY: ${{ secrets.MY_BLOG_DEPLOY_KEY }}
      - name: Prepare hexo and npm env
        run: |
          npm install -g hexo-cli
          npm install          
      - name: Prepare git env
        run: |
          git config --global user.email 13005465120@163.com
          git config --global user.name zzz1220      
      - name: Deploy Blog
        run: | 
          hexo clean
          hexo g
          hexo d
